repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: end-of-file-fixer
        stages: [commit]

      - id: trailing-whitespace
        stages: [push]

      - id: forbid-binary
        name: block-forbidden-words
        args: ['--text', '--pattern', 'TODO|FIXME']
        exclude: '^\.git/'
        stages: [push]
